---
- name: To create filesystem
  hosts: web
  become: yes

  tasks:
  - name: To check file exists
    command: ls /root/example.txt
    ignore_errors: yes
    notify:
      - restart_crond


  handlers:
    - name: restart_crond
      service:
        name: crond
        state: restarted
