apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: frontend
spec:
  replica: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: webapp
      labels:
        app: frontend
    spec:
      containers:
      - name: my-nginx
        image: nginx
