#This file is example for pulldata from secrets files via volumes
apiVersion: v1
kind: Pod
metadata:
   name: testing4
spec:
   containers:
   - name: testing4
     image: busybox
     command: ['sh','-c','while true;do sleep 10; done']
     volumeMounts:
     - name: my-vol1
       mountPath: /secret
   volumes:
   - name: my-vol1
     secret: 
       secretName: firstsec
