#This is a file where values are fetched from secret files.
apiVersion: v1
kind: Pod
metadata:
  name: testing2
spec:
  containers:
  - name : testing2
    image: busybox
    command: ['sh','-c','while true;do echo $SEC ;sleep 30;done']
    env:
      - name: SEC
        valueFrom:
          secretKeyRef:
            name: firstsec
            key: last 
